package com.example.blogapp.bean;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name="posts")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class Post {

	 @Id
	    @GeneratedValue(strategy = GenerationType.IDENTITY)
	    Long id;

	    @Column
	    String title;

	    @Column
	    String description;

	    @OneToMany(mappedBy = "post")
	    List<Comment> comments = new ArrayList<>();
	    
	    public Long getId() {
	        return id;
	    }
	    // Custom setter for id (if needed)
	    public void setId(Long id) {
	        this.id = id;
	    }
	    public String getTitle() {
	        return title;
	    }

	    // Setter for title (already generated by Lombok, but included manually for clarity)
	    public void setTitle(String title) {
	        this.title = title;
	    }

	    // Getter for description (already generated by Lombok)
	    public String getDescription() {
	        return description;
	    }

	    // Setter for description (already generated by Lombok, but included manually for clarity)
	    public void setDescription(String description) {
	        this.description = description;
	    }
	}